Migrating wiki to jetstream 2

diff --git a/ansible/custom_roles/confluence/templates/usr/share/confluence/bin/setenv.sh.j2 b/ansible/custom_roles/confluence/templates/usr/share/confluence/bin/setenv.sh.j2
--- a/ansible/custom_roles/confluence/templates/usr/share/confluence/bin/setenv.sh.j2
+++ b/ansible/custom_roles/confluence/templates/usr/share/confluence/bin/setenv.sh.j2
@@ -37,14 +37,93 @@ cd $PUSHED_DIR
 echo ""
 echo "Server startup logs are located in $LOGBASEABS/logs/catalina.out"
 
-# Set the JVM arguments used to start Confluence. For a description of the options, see
-# http://www.oracle.com/technetwork/java/javase/tech/vmoptions-jsp-140102.html
-CATALINA_OPTS="-XX:-PrintGCDetails -XX:+PrintGCTimeStamps -XX:-PrintTenuringDistribution ${CATALINA_OPTS}"
-CATALINA_OPTS="-Xloggc:$LOGBASEABS/logs/gc-`date +%F_%H-%M-%S`.log ${CATALINA_OPTS}"
-CATALINA_OPTS="-Djava.awt.headless=true ${CATALINA_OPTS}"
-CATALINA_OPTS="-Xms{{ confluence_jvm_minimum_memory }} -Xmx{{ confluence_jvm_maximum_memory }} -XX:+UseG1GC ${CATALINA_OPTS}"
+# IMPORTANT NOTE: Only set JAVA_HOME or JRE_HOME above this line
+# Get standard Java environment variables
+if $os400; then
+  # -r will Only work on the os400 if the files are:
+  # 1. owned by the user
+  # 2. owned by the PRIMARY group of the user
+  # this will not work if the user belongs in secondary groups
+  . "$CATALINA_HOME"/bin/setjre.sh
+else
+  if [ -r "$CATALINA_HOME"/bin/setjre.sh ]; then
+    . "$CATALINA_HOME"/bin/setjre.sh
+  else
+    echo "Cannot find $CATALINA_HOME/bin/setjre.sh"
+    echo "This file is needed to run this program"
+    exit 1
+  fi
+fi
 
+echo "---------------------------------------------------------------------------"
+echo "Using Java: $JRE_HOME/bin/java"
+CONFLUENCE_CONTEXT_PATH=`$JRE_HOME/bin/java -jar $CATALINA_HOME/bin/confluence-context-path-extractor.jar $CATALINA_HOME`
+export CONFLUENCE_CONTEXT_PATH
+$JRE_HOME/bin/java -jar $CATALINA_HOME/bin/synchrony-proxy-watchdog.jar $CATALINA_HOME
+echo "---------------------------------------------------------------------------"
+
+
+#----------------------------------------------------------------------------------- 
+# This section contains commonly modified Java options and system properties
+# When upgrading Confluence, copy this section to reapply your customizations
+# Always the review the new file for any changes to the default values
+
+# To learn more about Java 8 options see: 
+# https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html
+# To learn more about Java 11 options see: 
+# https://docs.oracle.com/en/java/javase/11/tools/java.html
+#-----------------------------------------------------------------------------------
+
+# Set the Java heap size
+CATALINA_OPTS="-Xms{{ confluence_jvm_minimum_memory }} -Xmx{{ confluence_jvm_maximum_memory }} ${CATALINA_OPTS}"
+
+# Default values for small to medium size instances
+# CATALINA_OPTS="-XX:ReservedCodeCacheSize=256m ${CATALINA_OPTS}"
+
+# Recommended values for medium to large, and enterprise size instances
+# Comment out the default values in the block above, then uncomment the values below
+# To learn more about the impact of disabling the upgrade recovery file see:
+# https://confluence.atlassian.com/x/ShtwPg
+CATALINA_OPTS="-XX:ReservedCodeCacheSize=384m ${CATALINA_OPTS}"
+CATALINA_OPTS="-XX:+PrintTenuringDistribution ${CATALINA_OPTS}"
+# CATALINA_OPTS="-XX:+PrintGCDetails -XX:+PrintGCTimeStamps ${CATALINA_OPTS}"
+CATALINA_OPTS="-Dconfluence.upgrade.recovery.file.enabled=false ${CATALINA_OPTS}"
+
+# Additional Confluence system properties
+# For a list of properties recognized by Confluence see:
+# https://confluence.atlassian.com/display/DOC/Recognized+System+Properties
+# We recommend you include a support ticket ID and/or note to help track the reason for change
+# For example:
+# CSP-123456 - Added example JVM option to help explain this section
+#CATALINA_OPTS="-Dexample.property=true ${CATALINA_OPTS}"
 CATALINA_OPTS="{{ confluence_jvm_support_recommended_args }} ${CATALINA_OPTS}"
+
+
 CATALINA_OPTS="-Dconfluence.home={{ confluence_home }} ${CATALINA_OPTS}"
 
+
+# Uncomment this line to disable email notifications
+#CATALINA_OPTS="-Datlassian.mail.senddisabled=true -Datlassian.mail.fetchdisabled=true ${CATALINA_OPTS}"
+
+#-----------------------------------------------------------------------------------
+# End of commonly modified Java options. You should not need to change the options 
+# below unless recommended by Atlassian Support
+#-----------------------------------------------------------------------------------
+
+CATALINA_OPTS="-XX:+IgnoreUnrecognizedVMOptions ${CATALINA_OPTS}"
+CATALINA_OPTS="-XX:G1ReservePercent=20 -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+PrintGCDateStamps ${CATALINA_OPTS}"
+CATALINA_OPTS="-Xlog:gc+age=debug:file=$LOGBASEABS/logs/gc-`date +%F_%H-%M-%S`.log::filecount=5,filesize=2M ${CATALINA_OPTS}"
+# CATALINA_OPTS="-Xloggc:$LOGBASEABS/logs/gc-`date +%F_%H-%M-%S`.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=2M ${CATALINA_OPTS}"
+CATALINA_OPTS="-Djava.awt.headless=true ${CATALINA_OPTS}"
+CATALINA_OPTS="-Datlassian.plugins.enable.wait=300 ${CATALINA_OPTS}"
+CATALINA_OPTS="-Dsynchrony.enable.xhr.fallback=true ${CATALINA_OPTS}"
+CATALINA_OPTS="-Djava.locale.providers=JRE,SPI,CLDR ${CATALINA_OPTS}"
+CATALINA_OPTS="-Dconfluence.context.path=${CONFLUENCE_CONTEXT_PATH} ${CATALINA_OPTS}"
+CATALINA_OPTS="-Dorg.apache.tomcat.websocket.DEFAULT_BUFFER_SIZE=32768 ${CATALINA_OPTS}"
+CATALINA_OPTS="${START_CONFLUENCE_JAVA_OPTS} ${CATALINA_OPTS}"
+
 export CATALINA_OPTS
+
+#-----------------------------------------------------------------------------------
+# End configuration options
+#-----------------------------------------------------------------------------------
